/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.LieMatrixCasimir
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.Data.Matrix.Bilinear

/-!
# Centrality and cyclic highest-weight Casimir eigenvalues

Centrality is derived from the actual matrix commutator relations. The
highest-weight eigenvalue then propagates through every generator word and
its linear span; the scalar Casimir identity is not an additional assumption.
-/
noncomputable section
open scoped BigOperators
open Matrix
namespace FreeEntropy.LieMatrixCasimir
set_option maxHeartbeats 800000
set_option linter.unusedSectionVars false
set_option backward.isDefEq.respectTransparency false
variable {d : ℕ} {H K : Type*} [Fintype H] [DecidableEq H]
  [Fintype K] [DecidableEq K]

theorem Generators.casimir_commutes (R : Generators d H) (k l : Fin d) :
    R.casimir * R.E k l = R.E k l * R.casimir := by
  apply sub_eq_zero.mp
  have ht (i j : Fin d) :
      (R.E i j * R.E j i) * R.E k l - R.E k l * (R.E i j * R.E j i) =
        ((if i = k then R.E i j * R.E j l else 0) -
          (if l = j then R.E i j * R.E k i else 0)) +
        ((if j = k then R.E i l * R.E j i else 0) -
          (if l = i then R.E k j * R.E j i else 0)) := by
    calc
      _ = R.E i j * (R.E j i * R.E k l - R.E k l * R.E j i) +
          (R.E i j * R.E k l - R.E k l * R.E i j) * R.E j i := by noncomm_ring
      _ = _ := by
        rw [R.commutator, R.commutator]
        simp only [Matrix.mul_sub, Matrix.sub_mul, mul_ite, ite_mul, mul_zero, zero_mul]
  simp only [Generators.casimir, Matrix.sum_mul, Matrix.mul_sum, ← Finset.sum_sub_distrib]
  simp_rw [ht, Finset.sum_add_distrib, Finset.sum_sub_distrib]
  simp only [Finset.sum_ite_eq, Finset.sum_ite_eq', Finset.mem_univ, if_true]
  rw [Finset.sum_comm]
  simp only [Finset.sum_ite_eq', Finset.mem_univ, if_true]
  rw [Finset.sum_comm]
  simp

/-- A genuine product of the matrix Lie generators. -/
def Generators.wordMatrix (R : Generators d H) (w : List (Fin d × Fin d)) : Matrix H H ℂ :=
  (w.map (fun p => R.E p.1 p.2)).prod

theorem Generators.casimir_commutes_word (R : Generators d H) (w : List (Fin d × Fin d)) :
    R.casimir * R.wordMatrix w = R.wordMatrix w * R.casimir := by
  induction w with
  | nil => simp [Generators.wordMatrix]
  | cons p w ih =>
    simp only [Generators.wordMatrix, List.map_cons, List.prod_cons] at ih ⊢
    rw [← Matrix.mul_assoc, R.casimir_commutes, Matrix.mul_assoc, ih, ← Matrix.mul_assoc]

/-- The Casimir eigenvalue extends to every word generated from a highest
weight subspace, including words with mixed raising and lowering generators. -/
theorem Generators.casimir_on_highest_word (R : Generators d H) (P : Matrix H K ℂ)
    (lam : Fin d → ℝ) (hweight : ∀ i, R.E i i * P = lam i • P)
    (hraise : ∀ i j, i < j → R.E i j * P = 0) (w : List (Fin d × Fin d)) :
    R.casimir * (R.wordMatrix w * P) = CasimirWeights.casimir lam • (R.wordMatrix w * P) := by
  rw [← Matrix.mul_assoc, R.casimir_commutes_word, Matrix.mul_assoc,
    R.casimir_on_highest P lam hweight hraise, Matrix.mul_smul]

/-- The actual cyclic matrix subspace generated by a highest-weight subspace. -/
def Generators.cyclicSpan (R : Generators d H) (P : Matrix H K ℂ) :
    Submodule ℂ (Matrix H K ℂ) :=
  Submodule.span ℂ (Set.range (fun w : List (Fin d × Fin d) => R.wordMatrix w * P))

/-- The Casimir polynomial acts on the full generated subspace. -/
theorem Generators.casimir_on_cyclicSpan (R : Generators d H) (P : Matrix H K ℂ)
    (lam : Fin d → ℝ) (hweight : ∀ i, R.E i i * P = lam i • P)
    (hraise : ∀ i j, i < j → R.E i j * P = 0)
    {X : Matrix H K ℂ} (hX : X ∈ R.cyclicSpan P) :
    R.casimir * X = CasimirWeights.casimir lam • X := by
  induction hX using Submodule.span_induction with
  | mem X hX =>
    obtain ⟨w, rfl⟩ := hX
    exact R.casimir_on_highest_word P lam hweight hraise w
  | zero => simp
  | add X Y _ _ hX hY => simp only [Matrix.mul_add, hX, hY, smul_add]
  | smul c X _ hX =>
    rw [Matrix.mul_smul, hX, smul_comm]

/-- If the highest-weight subspace is cyclic, the actual Casimir is the
scalar identity. Taking `K = Unit` gives the usual cyclic highest-vector case. -/
theorem Generators.casimir_eq_scalar_of_cyclic (R : Generators d H) [Nonempty K]
    (P : Matrix H K ℂ) (lam : Fin d → ℝ)
    (hweight : ∀ i, R.E i i * P = lam i • P)
    (hraise : ∀ i j, i < j → R.E i j * P = 0)
    (hcyclic : R.cyclicSpan P = ⊤) :
    R.casimir = CasimirWeights.casimir lam • (1 : Matrix H H ℂ) := by
  apply sub_eq_zero.mp
  apply (mulLeftLinearMap_eq_zero_iff (n := K) (R := ℂ) _).mp
  apply LinearMap.ext
  intro X
  have h := R.casimir_on_cyclicSpan P lam hweight hraise
    (X := X) (by rw [hcyclic]; trivial)
  change (R.casimir - CasimirWeights.casimir lam • (1 : Matrix H H ℂ)) * X = 0
  rw [Matrix.sub_mul, Matrix.smul_mul, Matrix.one_mul, h, sub_self]

end FreeEntropy.LieMatrixCasimir
