/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.UnitaryDecompositionBasic

/-! The actual cyclic subrepresentation generated by a vector. A unique joint
eigenline in a unitary representation generates an irreducible subrepresentation.
This supplies the irreducibility step for highest vectors in tensor products
of exterior powers, without assuming that their ambient representation is simple. -/

noncomputable section

namespace FreeEntropy.UnitaryDecomposition

variable {G E T : Type*} [Group G] [NormedAddCommGroup E]
  [InnerProductSpace ℂ E] [FiniteDimensional ℂ E]

/-- The subspace genuinely generated by the orbit of `v`. -/
def cyclicSubspace (ρ : Representation ℂ G E) (v : E) : Submodule ℂ E :=
  Submodule.span ℂ (Set.range (fun g : G => ρ g v))

theorem orbit_mem_cyclicSubspace (ρ : Representation ℂ G E) (v : E) (g : G) :
    ρ g v ∈ cyclicSubspace ρ v :=
  Submodule.subset_span ⟨g, rfl⟩

theorem mem_cyclicSubspace (ρ : Representation ℂ G E) (v : E) :
    v ∈ cyclicSubspace ρ v := by
  simpa using orbit_mem_cyclicSubspace ρ v 1

theorem cyclicSubspace_invariant (ρ : Representation ℂ G E) (v : E) :
    Invariant ρ (cyclicSubspace ρ v) := by
  intro g x hx
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    simpa only [map_mul, Module.End.mul_apply] using orbit_mem_cyclicSubspace ρ v (g * h)
  | zero => simpa using (cyclicSubspace ρ v).zero_mem
  | add x y hx hy hx' hy' => simpa using (cyclicSubspace ρ v).add_mem hx' hy'
  | smul c x hx hx' => simpa using (cyclicSubspace ρ v).smul_mem c hx'

theorem cyclicSubspace_le (ρ : Representation ℂ G E) (v : E)
    {K : Submodule ℂ E} (hK : Invariant ρ K) (hv : v ∈ K) :
    cyclicSubspace ρ v ≤ K := by
  apply Submodule.span_le.mpr
  rintro x ⟨g, rfl⟩
  exact hK g v hv

/-- Every nonzero vector in a genuine irreducible subspace is cyclic. -/
theorem cyclicSubspace_eq_of_irreducible (ρ : Representation ℂ G E)
    {K : Submodule ℂ E} (hK : IrreducibleSubspace ρ K) {v : E}
    (hvK : v ∈ K) (hv0 : v ≠ 0) : cyclicSubspace ρ v = K := by
  rcases hK.minimal (cyclicSubspace ρ v) (cyclicSubspace_invariant ρ v)
    (cyclicSubspace_le ρ v hK.invariant hvK) with hzero | heq
  · have hv := mem_cyclicSubspace ρ v
    rw [hzero] at hv
    exact False.elim (hv0 hv)
  · exact heq

/-- An eigenvalue of an operator commuting with the actual group action
propagates through the constructed cyclic subspace. -/
theorem operator_on_cyclicSubspace (ρ : Representation ℂ G E)
    (A : E →ₗ[ℂ] E) (c : ℂ) (v : E)
    (hcomm : ∀ g x, A (ρ g x) = ρ g (A x)) (hv : A v = c • v)
    {x : E} (hx : x ∈ cyclicSubspace ρ v) : A x = c • x := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨g, rfl⟩ := hx
    rw [hcomm, hv, map_smul]
  | zero => simp
  | add x y hx hy hx' hy' => simp [map_add, hx', hy', smul_add]
  | smul a x hx hx' => simp [map_smul, hx', smul_comm c a]

/-- An invariant projection preserves every simultaneous group eigenvector. -/
theorem projection_joint_eigenvector (ρ : Representation ℂ G E)
    (hstar : ∀ g, (ρ g).adjoint = ρ g⁻¹) {K : Submodule ℂ E}
    (hK : Invariant ρ K) (torus : T → G) (χ : T → ℂ) {v : E}
    (hv : ∀ t, ρ (torus t) v = χ t • v) (t : T) :
    ρ (torus t) (K.starProjection v) = χ t • K.starProjection v := by
  rw [← projection_commutes ρ hstar hK, hv t, map_smul]

/-- The cyclic orbit of a nonzero unique joint eigenvector is irreducible.
Only the eigenline is required to be unique; the ambient representation may
have arbitrarily many other irreducible constituents. -/
theorem cyclicSubspace_irreducible_of_unique_weight
    (ρ : Representation ℂ G E) (hstar : ∀ g, (ρ g).adjoint = ρ g⁻¹)
    (torus : T → G) (χ : T → ℂ) (v : E) (hv0 : v ≠ 0)
    (hv : ∀ t, ρ (torus t) v = χ t • v)
    (hunique : ∀ w : E, (∀ t, ρ (torus t) w = χ t • w) → ∃ c : ℂ, w = c • v) :
    IrreducibleSubspace ρ (cyclicSubspace ρ v) := by
  refine ⟨cyclicSubspace_invariant ρ v, ?_, ?_⟩
  · intro h
    have := mem_cyclicSubspace ρ v
    rw [h] at this
    exact hv0 this
  · intro K hK hKS
    obtain ⟨c, hc⟩ := hunique (K.starProjection v)
      (projection_joint_eigenvector ρ hstar hK torus χ hv)
    by_cases hc0 : c = 0
    · left
      have hPv : K.starProjection v = 0 := by simp [hc, hc0]
      have hzero (x : E) (hx : x ∈ cyclicSubspace ρ v) : K.starProjection x = 0 := by
        induction hx using Submodule.span_induction with
        | mem x hx =>
          obtain ⟨g, rfl⟩ := hx
          rw [projection_commutes ρ hstar hK, hPv, map_zero]
        | zero => exact map_zero _
        | add x y hx hy hx' hy' => simp [map_add, hx', hy']
        | smul a x hx hx' => simp [map_smul, hx']
      apply le_antisymm ?_ bot_le
      intro x hx
      change x = 0
      rw [← Submodule.starProjection_eq_self_iff.mpr hx]
      exact hzero x (hKS hx)
    · right
      apply le_antisymm hKS
      apply cyclicSubspace_le ρ v hK
      apply (Submodule.smul_mem_iff K hc0).mp
      rw [← hc]
      exact K.starProjection_apply_mem v

end FreeEntropy.UnitaryDecomposition
