/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.LieCyclicIrreducible

/-! A nonzero map out of a highest Lie-cyclic module is injective, and its
image is exactly the target Lie-cyclic space generated by the image vector. -/
noncomputable section
open Matrix
namespace FreeEntropy.LiePBW
open LieMatrixCasimir
set_option backward.isDefEq.respectTransparency false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000
variable {d : ℕ} {H K : Type*} [Fintype H] [DecidableEq H] [Fintype K] [DecidableEq K]

theorem intertwiner_word (R : Generators d H) (S : Generators d K)
    (f : (H → ℂ) →ₗ[ℂ] (K → ℂ))
    (hf : ∀ i j x, f (R.E i j *ᵥ x) = S.E i j *ᵥ f x)
    (w : List (Root d)) (v : H → ℂ) : f (word R w *ᵥ v) = word S w *ᵥ f v := by
  induction w with
  | nil => simp
  | cons a w ih => simp only [word_cons, ← Matrix.mulVec_mulVec, hf, ih]

theorem cyclic_intertwiner_injective (R : Generators d H) (S : Generators d K)
    (lam : Fin d → ℂ) (v : H → ℂ)
    (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0)
    (f : (H → ℂ) →ₗ[ℂ] (K → ℂ))
    (hf : ∀ i j x, f (R.E i j *ᵥ x) = S.E i j *ᵥ f x) (hfv : f v ≠ 0) :
    Function.Injective (f.comp (cyclicSpan R v).subtype) := by
  have hv : v ≠ 0 := fun h => hfv (by simp [h])
  let Z : Submodule ℂ (H → ℂ) := cyclicSpan R v ⊓ LinearMap.ker f
  have hZ : GeneratorInvariant R Z := by
    intro i j x hx
    refine ⟨generator_preserves_cyclicSpan R v i j hx.1, ?_⟩
    change f (R.E i j *ᵥ x) = 0
    rw [hf, show f x = 0 from hx.2, Matrix.mulVec_zero]
  have hzero : Z = ⊥ := by
    rcases cyclic_highest_irreducible R lam v hv hweight hraise Z hZ inf_le_left with hz | hz
    · exact hz
    · have hm : v ∈ Z := hz.symm ▸ self_mem_cyclicSpan R v
      exact (hfv hm.2).elim
  intro x y hxy
  have hm : (x : H → ℂ) - (y : H → ℂ) ∈ Z := by
    refine ⟨(cyclicSpan R v).sub_mem x.property y.property, ?_⟩
    change f ((x : H → ℂ) - y) = 0
    rw [map_sub, show f x = f y from hxy, sub_self]
  rw [hzero] at hm
  exact Subtype.ext (sub_eq_zero.mp hm)

theorem cyclic_intertwiner_surjective (R : Generators d H) (S : Generators d K)
    (v : H → ℂ) (f : (H → ℂ) →ₗ[ℂ] (K → ℂ))
    (hf : ∀ i j x, f (R.E i j *ᵥ x) = S.E i j *ᵥ f x)
    (hcyc : cyclicSpan S (f v) = ⊤) :
    Function.Surjective (f.comp (cyclicSpan R v).subtype) := by
  apply LinearMap.range_eq_top.mp
  apply top_unique
  rw [← hcyc]
  apply Submodule.span_le.mpr
  rintro _ ⟨w, rfl⟩
  refine ⟨⟨word R w *ᵥ v, Submodule.subset_span ⟨w, rfl⟩⟩, ?_⟩
  exact intertwiner_word R S f hf w v

/-- The map is an actual linear equivalence on the source cyclic space. -/
def cyclicIntertwinerEquiv (R : Generators d H) (S : Generators d K)
    (lam : Fin d → ℂ) (v : H → ℂ)
    (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0)
    (f : (H → ℂ) →ₗ[ℂ] (K → ℂ))
    (hf : ∀ i j x, f (R.E i j *ᵥ x) = S.E i j *ᵥ f x) (hfv : f v ≠ 0)
    (hcyc : cyclicSpan S (f v) = ⊤) : cyclicSpan R v ≃ₗ[ℂ] (K → ℂ) :=
  LinearEquiv.ofBijective (f.comp (cyclicSpan R v).subtype)
    ⟨cyclic_intertwiner_injective R S lam v hweight hraise f hf hfv,
      cyclic_intertwiner_surjective R S v f hf hcyc⟩

end FreeEntropy.LiePBW
