/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.LiePBWUnique
import FreeEntropy.UnitaryDecompositionBasic

/-! A highest-weight Lie-cyclic space is genuinely irreducible under its
actual star-closed generators, by orthogonal projection and PBW uniqueness. -/
noncomputable section
open Matrix
open scoped ComplexInnerProductSpace
namespace FreeEntropy.LiePBW
open LieMatrixCasimir
set_option backward.isDefEq.respectTransparency false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000
variable {d : ℕ} {H : Type*} [Fintype H] [DecidableEq H]

def GeneratorInvariant (R : Generators d H) (S : Submodule ℂ (H → ℂ)) : Prop :=
  ∀ i j x, x ∈ S → R.E i j *ᵥ x ∈ S

def hilbertSubspace (S : Submodule ℂ (H → ℂ)) : Submodule ℂ (EuclideanSpace ℂ H) :=
  S.comap (EuclideanSpace.equiv H ℂ).toLinearEquiv.toLinearMap

def projectionMatrix (S : Submodule ℂ (H → ℂ)) : Matrix H H ℂ :=
  Matrix.toEuclideanLin.symm (hilbertSubspace S).starProjection.toLinearMap

theorem projectionMatrix_apply (S : Submodule ℂ (H → ℂ)) (x : H → ℂ) :
    projectionMatrix S *ᵥ x = ((hilbertSubspace S).starProjection (WithLp.toLp 2 x)).ofLp := by
  have h := congrArg (fun f : EuclideanSpace ℂ H →ₗ[ℂ] EuclideanSpace ℂ H =>
    (f (WithLp.toLp 2 x)).ofLp) (Matrix.toEuclideanLin.apply_symm_apply
      (hilbertSubspace S).starProjection.toLinearMap)
  simpa only [projectionMatrix, Matrix.toLpLin_apply] using h

theorem projectionMatrix_mem (S : Submodule ℂ (H → ℂ)) (x : H → ℂ) :
    projectionMatrix S *ᵥ x ∈ S := by
  rw [projectionMatrix_apply]
  exact (hilbertSubspace S).starProjection_apply_mem _

theorem projectionMatrix_fix {S : Submodule ℂ (H → ℂ)} {x : H → ℂ} (hx : x ∈ S) :
    projectionMatrix S *ᵥ x = x := by
  rw [projectionMatrix_apply]
  have h := Submodule.starProjection_eq_self_iff.mpr
    (show WithLp.toLp 2 x ∈ hilbertSubspace S from hx)
  rw [h]

theorem projectionMatrix_commutes (R : Generators d H) {S : Submodule ℂ (H → ℂ)}
    (hS : GeneratorInvariant R S) (i j : Fin d) :
    projectionMatrix S * R.E i j = R.E i j * projectionMatrix S := by
  have hK (a b : Fin d) (x : EuclideanSpace ℂ H) (hx : x ∈ hilbertSubspace S) :
      Matrix.toEuclideanLin (R.E a b) x ∈ hilbertSubspace S := hS a b x.ofLp hx
  have hp (x : EuclideanSpace ℂ H) :
      (hilbertSubspace S).starProjection (Matrix.toEuclideanLin (R.E i j) x) =
      Matrix.toEuclideanLin (R.E i j) ((hilbertSubspace S).starProjection x) := by
    apply Submodule.eq_starProjection_of_mem_of_inner_eq_zero
    · exact hK i j _ ((hilbertSubspace S).starProjection_apply_mem x)
    · intro y hy
      rw [← map_sub, ← LinearMap.adjoint_inner_right,
        ← Matrix.toEuclideanLin_conjTranspose_eq_adjoint, R.adjoint]
      exact (hilbertSubspace S).starProjection_inner_eq_zero x _ (hK j i y hy)
  have hmul (A B : Matrix H H ℂ) (x : EuclideanSpace ℂ H) :
      Matrix.toEuclideanLin (A * B) x = Matrix.toEuclideanLin A (Matrix.toEuclideanLin B x) := by
    simp only [Matrix.toLpLin_apply, Matrix.mulVec_mulVec]
  apply Matrix.toEuclideanLin.injective
  apply LinearMap.ext
  intro x
  simp only [hmul, projectionMatrix, LinearEquiv.apply_symm_apply]
  exact hp x

theorem cyclicSpan_le_of_invariant (R : Generators d H) (v : H → ℂ)
    {S : Submodule ℂ (H → ℂ)} (hS : GeneratorInvariant R S) (hv : v ∈ S) :
    cyclicSpan R v ≤ S := by
  apply Submodule.span_le.mpr
  rintro _ ⟨w, rfl⟩
  induction w with
  | nil => simpa using hv
  | cons a w ih => simpa only [word_cons, ← Matrix.mulVec_mulVec] using hS a.1 a.2 _ ih

theorem commuting_operator_scalar_on_cyclicSpan (R : Generators d H) (v : H → ℂ)
    (T : Matrix H H ℂ) (hT : ∀ i j, T * R.E i j = R.E i j * T)
    (c : ℂ) (hv : T *ᵥ v = c • v) {x : H → ℂ} (hx : x ∈ cyclicSpan R v) :
    T *ᵥ x = c • x := by
  have hw (w : List (Root d)) : T *ᵥ (word R w *ᵥ v) = c • (word R w *ᵥ v) := by
    induction w with
    | nil => simpa using hv
    | cons a w ih =>
      rw [word_cons, ← Matrix.mulVec_mulVec, Matrix.mulVec_mulVec,
        hT, ← Matrix.mulVec_mulVec, ih, Matrix.mulVec_smul]
  induction hx using Submodule.span_induction with
  | mem x hx => obtain ⟨w, rfl⟩ := hx; exact hw w
  | zero => simp
  | add x y hx hy ihx ihy => simp only [Matrix.mulVec_add, ihx, ihy, smul_add]
  | smul a x hx ih => simp only [Matrix.mulVec_smul, ih, smul_comm a c]

/-- There is no proper nonzero invariant subspace inside the Lie module
generated by a highest vector. -/
theorem cyclic_highest_irreducible (R : Generators d H) (lam : Fin d → ℂ) (v : H → ℂ)
    (hv : v ≠ 0) (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0)
    (S : Submodule ℂ (H → ℂ)) (hS : GeneratorInvariant R S) (hle : S ≤ cyclicSpan R v) :
    S = ⊥ ∨ S = cyclicSpan R v := by
  let P := projectionMatrix S
  have hcomm := projectionMatrix_commutes R hS
  have hpv : P *ᵥ v ∈ cyclicSpan R v := hle (projectionMatrix_mem S v)
  have hpraise (i j : Fin d) (hij : i < j) : R.E i j *ᵥ (P *ᵥ v) = 0 := by
    rw [Matrix.mulVec_mulVec, ← hcomm, ← Matrix.mulVec_mulVec, hraise i j hij, Matrix.mulVec_zero]
  obtain ⟨c, hc⟩ := highest_line_unique R lam v (P *ᵥ v) hv hweight hraise hpv hpraise
  by_cases hc0 : c = 0
  · left
    apply le_antisymm ?_ bot_le
    intro x hx
    have he := commuting_operator_scalar_on_cyclicSpan R v P hcomm c hc (hle hx)
    rw [projectionMatrix_fix hx, hc0, zero_smul] at he
    exact he
  · right
    apply le_antisymm hle
    apply cyclicSpan_le_of_invariant R v hS
    apply (Submodule.smul_mem_iff S hc0).mp
    rw [← hc]
    exact projectionMatrix_mem S v

end FreeEntropy.LiePBW
