/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.LiePBW

/-! The entire Lie-cyclic space of an actual highest vector is generated by
lowering words. This is derived from the proved matrix PBW spanning lemma. -/
noncomputable section
open Matrix
namespace FreeEntropy.LiePBW
open LieMatrixCasimir
set_option backward.isDefEq.respectTransparency false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

variable {d : ℕ} {H : Type*} [Fintype H] [DecidableEq H]

/-- A word in diagonal and raising matrices acts on a highest vector as a scalar. -/
theorem nonlower_word_scalar (R : Generators d H) (lam : Fin d → ℂ) (v : H → ℂ)
    (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0)
    (w : List (Root d)) (hw : ∀ a ∈ w, ¬ a.2 < a.1) :
    ∃ c : ℂ, word R w *ᵥ v = c • v := by
  induction w with
  | nil => exact ⟨1, by simp⟩
  | cons a w ih =>
    obtain ⟨c, hc⟩ := ih (fun b hb => hw b (List.mem_cons_of_mem a hb))
    rw [word_cons, ← Matrix.mulVec_mulVec, hc, Matrix.mulVec_smul]
    by_cases ha : a.1 = a.2
    · refine ⟨c * lam a.1, ?_⟩
      rw [← ha, hweight, smul_smul]
    · have hlt : a.1 < a.2 := lt_of_le_of_ne
        (le_of_not_gt (hw a List.mem_cons_self)) ha
      refine ⟨0, ?_⟩
      rw [hraise a.1 a.2 hlt, smul_zero, zero_smul]

/-- A sorted word reduces to one scalar multiple of a lowering word. -/
theorem ordered_word_scalar_lowering (R : Generators d H) (lam : Fin d → ℂ) (v : H → ℂ)
    (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0)
    (w : List (Root d)) (hw : w.Pairwise (fun a b => kind a ≤ kind b)) :
    ∃ l : List (Root d), (∀ a ∈ l, a.2 < a.1) ∧
      ∃ c : ℂ, word R w *ᵥ v = c • (word R l *ᵥ v) := by
  induction w with
  | nil => exact ⟨[], by simp, 1, by simp⟩
  | cons a w ih =>
    obtain ⟨hab, htail⟩ := List.pairwise_cons.mp hw
    by_cases ha : a.2 < a.1
    · obtain ⟨l, hl, c, hc⟩ := ih htail
      refine ⟨a :: l, ?_, c, ?_⟩
      · intro b hb
        rcases List.mem_cons.mp hb with rfl | hb
        · exact ha
        · exact hl b hb
      · simp only [word_cons, ← Matrix.mulVec_mulVec, hc, Matrix.mulVec_smul]
    · have hn : ∀ b ∈ a :: w, ¬ b.2 < b.1 := by
        intro b hb
        rcases List.mem_cons.mp hb with rfl | hb
        · exact ha
        · intro hbl
          have he := hab b hb
          simp only [kind, if_pos hbl, if_neg ha] at he
          split_ifs at he <;> omega
      obtain ⟨c, hc⟩ := nonlower_word_scalar R lam v hweight hraise (a :: w) hn
      exact ⟨[], by simp, c, by simpa only [word_nil, Matrix.one_mulVec] using hc⟩

def cyclicSpan (R : Generators d H) (v : H → ℂ) : Submodule ℂ (H → ℂ) :=
  Submodule.span ℂ {x | ∃ w : List (Root d), word R w *ᵥ v = x}

def loweringSpan (R : Generators d H) (v : H → ℂ) : Submodule ℂ (H → ℂ) :=
  Submodule.span ℂ {x | ∃ w : List (Root d), (∀ a ∈ w, a.2 < a.1) ∧ word R w *ᵥ v = x}

theorem word_action_mem_loweringSpan (R : Generators d H) (lam : Fin d → ℂ) (v : H → ℂ)
    (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0) (w : List (Root d)) :
    word R w *ᵥ v ∈ loweringSpan R v := by
  have hm := word_mem_orderedSpan R kind w
  generalize he : word R w = M at hm ⊢
  clear he w
  change M ∈ Submodule.span ℂ _ at hm
  induction hm using Submodule.span_induction with
  | mem M hM =>
    obtain ⟨t, ht, rfl⟩ := hM
    obtain ⟨l, hl, c, hc⟩ := ordered_word_scalar_lowering R lam v hweight hraise t ht
    rw [hc]
    exact (loweringSpan R v).smul_mem c (Submodule.subset_span ⟨l, hl, rfl⟩)
  | zero => simp
  | add M N hM hN ihM ihN =>
    simpa only [Matrix.add_mulVec] using (loweringSpan R v).add_mem ihM ihN
  | smul c M hM ihM =>
    simpa only [Matrix.smul_mulVec] using (loweringSpan R v).smul_mem c ihM

/-- The Lie-cyclic span is exactly the span of lowering words. -/
theorem cyclicSpan_eq_loweringSpan (R : Generators d H) (lam : Fin d → ℂ) (v : H → ℂ)
    (hweight : ∀ i, R.E i i *ᵥ v = lam i • v)
    (hraise : ∀ i j, i < j → R.E i j *ᵥ v = 0) :
    cyclicSpan R v = loweringSpan R v := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨w, rfl⟩
    exact word_action_mem_loweringSpan R lam v hweight hraise w
  · apply Submodule.span_mono
    rintro _ ⟨w, _, rfl⟩
    exact ⟨w, rfl⟩

theorem self_mem_cyclicSpan (R : Generators d H) (v : H → ℂ) : v ∈ cyclicSpan R v :=
  Submodule.subset_span ⟨[], by simp⟩

theorem generator_preserves_cyclicSpan (R : Generators d H) (v : H → ℂ)
    (i j : Fin d) {x : H → ℂ} (hx : x ∈ cyclicSpan R v) : R.E i j *ᵥ x ∈ cyclicSpan R v := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w, rfl⟩ := hx
    exact Submodule.subset_span ⟨(i, j) :: w, by simp [Matrix.mulVec_mulVec]⟩
  | zero => simp
  | add x y hx hy ihx ihy =>
    simpa only [Matrix.mulVec_add] using (cyclicSpan R v).add_mem ihx ihy
  | smul c x hx ih =>
    simpa only [Matrix.mulVec_smul] using (cyclicSpan R v).smul_mem c ih

end FreeEntropy.LiePBW
