/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.TensorSites
import Mathlib.RingTheory.MvPolynomial.Symmetric.NewtonIdentities
import Mathlib.Algebra.Algebra.Subalgebra.Lattice

/-! Newton identities recover actual tensor powers from the infinitesimal
single-site sums. In particular the physical Lie and unitary commutants coincide. -/

noncomputable section
open Matrix
open scoped BigOperators

namespace FreeEntropy.TensorPowers
set_option backward.isDefEq.respectTransparency false

/-- In characteristic zero, the power sums generate the product of a finite
commuting family. This is the exact finite Newton-identity argument. -/
theorem prod_mem_of_powerSum_mem {ι S : Type*} [Fintype ι]
    [CommRing S] [Algebra ℂ S] (B : Subalgebra ℂ S) (x : ι → S)
    (hx : ∀ k : ℕ, (∑ i, x i ^ k) ∈ B) : (∏ i, x i) ∈ B := by
  classical
  let ev : MvPolynomial ι ℂ →ₐ[ℂ] S := MvPolynomial.aeval x
  have he : ∀ k : ℕ, ev (MvPolynomial.esymm ι ℂ k) ∈ B := by
    intro k
    induction k using Nat.strong_induction_on with
    | h k ih =>
      by_cases hk : k = 0
      · subst k; simp
      have hn : (k : ℂ) ≠ 0 := by exact_mod_cast hk
      have hnew := congrArg ev (MvPolynomial.mul_esymm_eq_sum ι ℂ k)
      simp only [map_mul, map_pow, map_neg, map_one, map_sum, map_natCast] at hnew
      have hm : (k : S) * ev (MvPolynomial.esymm ι ℂ k) ∈ B := by
        rw [hnew]
        apply B.mul_mem
        · exact B.pow_mem (B.neg_mem B.one_mem) _
        · apply B.sum_mem
          intro a ha
          apply B.mul_mem
          · apply B.mul_mem
            · exact B.pow_mem (B.neg_mem B.one_mem) _
            · exact ih a.1 (Finset.mem_filter.mp ha).2
          · simpa [ev, MvPolynomial.psum] using hx a.2
      have hm' : (k : ℂ) • ev (MvPolynomial.esymm ι ℂ k) ∈ B := by
        simpa [Algebra.smul_def] using hm
      have := B.smul_mem hm' (k : ℂ)⁻¹
      simpa [smul_smul, hn] using this
  have hc : Finset.powersetCard (Fintype.card ι) (Finset.univ : Finset ι) = {Finset.univ} := by
    simpa using Finset.powersetCard_self (Finset.univ : Finset ι)
  simpa [ev, MvPolynomial.esymm, hc] using he (Fintype.card ι)

variable {H : Type*} [Fintype H] [DecidableEq H] {n : ℕ}

theorem site_one (t : Fin n) : site t (1 : Matrix H H ℂ) = 1 := by
  simpa [site, Function.update_eq_self, family] using (matrix_one (H := H) n)

theorem site_pow (t : Fin n) (A : Matrix H H ℂ) (k : ℕ) :
    site t (A ^ k) = site t A ^ k := by
  induction k with
  | zero => simp [site_one]
  | succ k ih => rw [pow_succ, site_mul, ih, pow_succ]

/-- The commutative algebra generated by the commuting copies of a single
matrix on the separate tensor factors. -/
def siteAlgebra (A : Matrix H H ℂ) :
    Subalgebra ℂ (Matrix (Fin n → H) (Fin n → H) ℂ) :=
  Algebra.adjoin ℂ (Set.range fun t : Fin n => site t A)

def siteAlgebraElement (A : Matrix H H ℂ) (t : Fin n) : siteAlgebra (n := n) A :=
  ⟨site t A, Algebra.subset_adjoin (Set.mem_range_self t)⟩

instance siteAlgebra.commRing (A : Matrix H H ℂ) : CommRing (siteAlgebra (n := n) A) :=
  Algebra.adjoinCommRingOfComm ℂ (by
    rintro _ ⟨s, rfl⟩ _ ⟨t, rfl⟩
    by_cases h : s = t
    · subst t; rfl
    · exact site_commute s t h A A)

/-- Multiplying the single-site copies gives the actual tensor matrix. -/
theorem siteAlgebra_prod (A : Matrix H H ℂ) :
    ((∏ t : Fin n, siteAlgebraElement A t : siteAlgebra A) :
      Matrix (Fin n → H) (Fin n → H) ℂ) = matrix n A := by
  have h (s : Finset (Fin n)) :
      ((∏ t ∈ s, siteAlgebraElement A t : siteAlgebra A) :
        Matrix (Fin n → H) (Fin n → H) ℂ) =
        family (fun t => if t ∈ s then A else 1) := by
    induction s using Finset.induction_on with
    | empty => simpa [family] using (matrix_one (H := H) n).symm
    | @insert t s hts ih =>
      rw [Finset.prod_insert hts, Subalgebra.coe_mul, ih]
      change site t A * family _ = _
      rw [site, ← family_mul]
      congr 1
      funext u
      by_cases hut : u = t
      · subst u; simp [hts]
      · simp [hut]
  simpa [family, matrix] using h Finset.univ

/-- Every tensor power lies in the algebra detected by all infinitesimal
commutation identities. No self-adjointness or invertibility is required. -/
theorem commutes_matrix_of_commutes_differential
    (T : Matrix (Fin n → H) (Fin n → H) ℂ)
    (hT : ∀ A : Matrix H H ℂ, T * differential n A = differential n A * T)
    (A : Matrix H H ℂ) : T * matrix n A = matrix n A * T := by
  let B : Subalgebra ℂ (siteAlgebra (n := n) A) :=
    (Subalgebra.centralizer ℂ ({T} : Set (Matrix (Fin n → H) (Fin n → H) ℂ))).comap
      (siteAlgebra A).val
  have hs (k : ℕ) : (∑ t : Fin n, siteAlgebraElement A t ^ k) ∈ B := by
    change (↑(∑ t : Fin n, siteAlgebraElement A t ^ k) :
      Matrix (Fin n → H) (Fin n → H) ℂ) ∈ Subalgebra.centralizer ℂ {T}
    change (siteAlgebra A).val (∑ t : Fin n, siteAlgebraElement A t ^ k) ∈ _
    simp only [map_sum, map_pow]
    change (∑ t : Fin n, site t A ^ k) ∈ _
    rw [Subalgebra.mem_centralizer_iff]
    rintro _ (rfl : _ = T)
    simpa only [← site_pow, ← differential_eq_sum_sites] using hT (A ^ k)
  have hm := prod_mem_of_powerSum_mem B (siteAlgebraElement A) hs
  change (↑(∏ t : Fin n, siteAlgebraElement A t) :
    Matrix (Fin n → H) (Fin n → H) ℂ) ∈ Subalgebra.centralizer ℂ {T} at hm
  rw [siteAlgebra_prod] at hm
  exact ((Subalgebra.mem_centralizer_iff ℂ).mp hm) T (Set.mem_singleton T)

/-- The infinitesimal action is a complex linear map. -/
def differentialLinearMap (n : ℕ) :
    Matrix H H ℂ →ₗ[ℂ] Matrix (Fin n → H) (Fin n → H) ℂ where
  toFun := differential n
  map_add' := differential_add n
  map_smul' := differential_smul n

/-- It suffices to check the literal matrix-unit Lie generators. -/
theorem commutes_differential_of_commutes_generators
    (T : Matrix (Fin n → H) (Fin n → H) ℂ)
    (hT : ∀ i j : H, T * differential n (single i j 1) =
      differential n (single i j 1) * T)
    (A : Matrix H H ℂ) : T * differential n A = differential n A * T := by
  have hA : A = ∑ i, ∑ j, A i j • single i j (1 : ℂ) := by
    simpa only [Matrix.smul_single, smul_eq_mul, mul_one] using Matrix.matrix_eq_sum_single A
  change T * differentialLinearMap n A = differentialLinearMap n A * T
  rw [hA]
  simp only [map_sum, map_smul, Matrix.mul_sum, Matrix.sum_mul,
    Matrix.mul_smul, Matrix.smul_mul]
  apply Finset.sum_congr rfl
  intro i _
  apply Finset.sum_congr rfl
  intro j _
  exact congrArg (A i j • ·) (hT i j)

/-- The full tensor representation is recovered algebraically from its
matrix-unit differential action. -/
theorem commutes_matrix_of_commutes_generators
    (T : Matrix (Fin n → H) (Fin n → H) ℂ)
    (hT : ∀ i j : H, T * differential n (single i j 1) =
      differential n (single i j 1) * T)
    (A : Matrix H H ℂ) : T * matrix n A = matrix n A * T :=
  commutes_matrix_of_commutes_differential T
    (commutes_differential_of_commutes_generators T hT) A

end FreeEntropy.TensorPowers

namespace FreeEntropy.SchurWeyl

/-- Exact coincidence of the physical unitary commutant and the commutant
of the actual raising, lowering, and diagonal Lie generators. -/
theorem tensorCommutant_iff_generators {d n : ℕ}
    (T : Matrix (Fin n → Fin d) (Fin n → Fin d) ℂ) :
    TensorCommutant T ↔ ∀ i j : Fin d,
      T * (TensorPowers.generators d n).E i j =
        (TensorPowers.generators d n).E i j * T := by
  constructor
  · intro h i j
    exact h.differential (single i j 1)
  · intro h U
    exact TensorPowers.commutes_matrix_of_commutes_generators T h U.val

end FreeEntropy.SchurWeyl
