/-
Copyright (c) 2026 Free Entropy formalization contributors.
See LICENSE and NOTICE in the repository root for license and attribution.
-/

import FreeEntropy.TensorLieCyclicitySubspace
import FreeEntropy.TensorHighestWeight
import FreeEntropy.LiePBWUnique

/-! Every constructed physical Schur sector has an actual dominant highest
vector, is generated by its lowering operators, and has one highest line. -/
noncomputable section
open Matrix

namespace FreeEntropy.SchurWeyl
open Occupation
set_option backward.isDefEq.respectTransparency false
variable {d n : ℕ}

/-- The genuine compressed Lie matrices on a constructed physical sector. -/
def sectorGenerators (i : Sector d n) :
    LieMatrixCasimir.Generators d (SectorSpace d n i) :=
  restrictedGenerators ((physicalDecomposition d n).representation i)
    ((physicalDecomposition d n).embedding i) ((physicalDecomposition d n).isometry i)
    ((physicalDecomposition d n).intertwines i)

/-- Actual irreducibility implies Lie cyclicity for every nonzero sector vector. -/
theorem sector_cyclicSpan_eq_top (i : Sector d n) (v : SectorSpace d n i → ℂ) (hv : v ≠ 0) :
    LiePBW.cyclicSpan (sectorGenerators i) v = ⊤ :=
  restricted_cyclicSpan_eq_top ((physicalDecomposition d n).representation i)
    ((physicalDecomposition d n).embedding i) ((physicalDecomposition d n).isometry i)
    ((physicalDecomposition d n).intertwines i) ((physicalDecomposition d n).irreducible i) v hv

/-- Every actual tensor sector has a dominant natural highest weight and a
nonzero highest vector whose Lie orbit spans the whole sector. -/
theorem exists_sector_highest (i : Sector d n) :
    ∃ a : Occupation d n, ∃ v : SectorSpace d n i → ℂ,
      v ≠ 0 ∧ Antitone a.val ∧
      (∀ j, (sectorGenerators i).E j j *ᵥ v = (a.val j : ℂ) • v) ∧
      (∀ j k, j < k → (sectorGenerators i).E j k *ᵥ v = 0) ∧
      LiePBW.cyclicSpan (sectorGenerators i) v = ⊤ := by
  obtain ⟨a, w, hwK, hw0, hweight, hdom, hraise, _⟩ := physical_sector_highest i
  let J := (physicalDecomposition d n).embedding i
  let v := Jᴴ *ᵥ w.ofLp
  have hJv : J *ᵥ v = w.ofLp := by
    have hp := UnitaryDecomposition.embedding_projection i.val w
    rw [Submodule.starProjection_eq_self_iff.mpr hwK] at hp
    simpa only [Matrix.toLpLin_apply, WithLp.ofLp_toLp, ← Matrix.mulVec_mulVec] using
      congrArg WithLp.ofLp hp
  have hv : v ≠ 0 := by
    intro hv
    have hw : w.ofLp = 0 := by rw [← hJv, hv, Matrix.mulVec_zero]
    exact hw0 (WithLp.ofLp_injective 2 hw)
  have hact (j k : Fin d) : (sectorGenerators i).E j k *ᵥ v =
      Jᴴ *ᵥ ((TensorPowers.generators d n).E j k *ᵥ w.ofLp) := by
    change (Jᴴ * (TensorPowers.generators d n).E j k * J) *ᵥ v = _
    rw [← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec, hJv]
  refine ⟨a, v, hv, hdom, ?_, ?_, sector_cyclicSpan_eq_top i v hv⟩
  · intro j
    rw [hact, hweight j, Matrix.mulVec_smul]
  · intro j k hjk
    rw [hact, hraise j k hjk, Matrix.mulVec_zero]

/-- The full actual sector is generated by lowering words from its highest
vector. This combines proved cyclicity with the proved finite PBW theorem. -/
theorem exists_sector_lowering_generator (i : Sector d n) :
    ∃ a : Occupation d n, ∃ v : SectorSpace d n i → ℂ,
      v ≠ 0 ∧ Antitone a.val ∧
      (∀ j, (sectorGenerators i).E j j *ᵥ v = (a.val j : ℂ) • v) ∧
      (∀ j k, j < k → (sectorGenerators i).E j k *ᵥ v = 0) ∧
      LiePBW.loweringSpan (sectorGenerators i) v = ⊤ := by
  obtain ⟨a, v, hv, hdom, hweight, hraise, hcyclic⟩ := exists_sector_highest i
  exact ⟨a, v, hv, hdom, hweight, hraise,
    (LiePBW.cyclicSpan_eq_loweringSpan (sectorGenerators i) (fun j => (a.val j : ℂ))
      v hweight hraise).symm.trans hcyclic⟩

/-- The highest line of every actual physical sector is one-dimensional.
There is no supplied highest-weight multiplicity or cyclicity hypothesis. -/
theorem exists_sector_unique_highest (i : Sector d n) :
    ∃ a : Occupation d n, ∃ v : SectorSpace d n i → ℂ,
      v ≠ 0 ∧ Antitone a.val ∧
      (∀ j, (sectorGenerators i).E j j *ᵥ v = (a.val j : ℂ) • v) ∧
      (∀ j k, j < k → (sectorGenerators i).E j k *ᵥ v = 0) ∧
      ∀ u : SectorSpace d n i → ℂ,
        (∀ j k, j < k → (sectorGenerators i).E j k *ᵥ u = 0) → ∃ c : ℂ, u = c • v := by
  obtain ⟨a, v, hv, hdom, hweight, hraise, hcyclic⟩ := exists_sector_highest i
  refine ⟨a, v, hv, hdom, hweight, hraise, ?_⟩
  intro u hu
  exact LiePBW.highest_line_unique (sectorGenerators i) (fun j => (a.val j : ℂ)) v u
    hv hweight hraise (by rw [hcyclic]; trivial) hu

end FreeEntropy.SchurWeyl
